name: Sync to Gitee

on:
  push:
    branches: [dev]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build site
        run: cd packages/varlet-ui && yarn build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-page
          folder: packages/varlet-ui/site

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:haoziqaq/varlet.git
          destination-repo: git@gitee.com:varlet/varlet-ui.git
