name: Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build site
        run: cd packages/varlet-ui && yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: packages/varlet-ui/site/

      - name: Save pr number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr.txt

      - name: Upload pr number
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr.txt
          retention-days: 1
